###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   Batteries
#   @description    :   Status about various baterries (iphones, sensors...etc)
###############################################################################
homeassistant:
  customize:

    group.batteries:
      order: 2

    sensor.sureshs_iphone_battery_state:
      hidden: true
    sensor.mallikas_iphone_battery_state:
      hidden: true
    sensor.srinikas_iphone_battery_state:
      hidden: true
    sensor.hasikas_iphone_battery_state:
      hidden: true

    sensor.sureshs_iphone_battery_ot:
      hidden: true
    sensor.mallikas_iphone_battery_ot:
      hidden: true
    sensor.srinikas_iphone_battery_ot:
      hidden: true
    sensor.hasikas_iphone_battery_ot:
      hidden: true

    sensor.suresh_iphone_battery_ot:
      friendly_name: Suresh's iPhone Battery
    sensor.mallika_iphone_battery_ot:
      friendly_name: Mallika's iPhone Battery
    sensor.srinika_iphone_battery_ot:
      friendly_name: Srinika's iPhone Battery
    sensor.hasika_iphone_battery_ot:
      friendly_name: Hasika's iPhone Battery

    sensor.hasikas_iphone_wifi_state:
      friendly_name: Hasika's Phone Wi-Fi Status
    sensor.mallikas_iphone_wifi_state:
      friendly_name: Mallika's Phone Wi-Fi Status
    sensor.srinikas_iphone_wifi_state:
      friendly_name: Srinika's Phone Wi-Fi Status
    sensor.sureshs_iphone_wifi_state:
      friendly_name: Suresh's Phone Wi-Fi Status

# Multi Sensor Batteries
    sensor.upstairs_multisensor_battery:
      friendly_name: Upstairs Multisensor Battery
    sensor.downstairs_multisensor_battery:
      friendly_name: Downstairs Multisensor Battery
    sensor.front_door_sensor_battery:
      friendly_name: Front Door Sensor Battery
    sensor.back_door_sensor_battery:
      friendly_name: Back Door Sensor Battery
    sensor.single_car_garage_door_sensor_battery:
      friendly_name: Single Car Garage Door Sensor Battery
    sensor.two_car_garage_door_sensor_battery:
      friendly_name: Two Car Garage Door Sensor Battery
    automation.alert_low_battery_level_of_multisensors:
      friendly_name: Alert Low Battery of Multisensors

group:
  Batteries:
    entities:
      - sensor.suresh_iphone_battery_ot
      - sensor.mallika_iphone_battery_ot
      - sensor.srinika_iphone_battery_ot
      - sensor.hasika_iphone_battery_ot
      
      - sensor.front_door_sensor_battery
      - sensor.back_door_sensor_battery
      - sensor.frontroom_multisensor_battery
      - sensor.upstairs_multisensor_battery
      - sensor.downstairs_multisensor_battery
      - sensor.single_car_garage_door_sensor_battery
      - sensor.two_car_garage_door_sensor_battery
      - automation.alert_low_battery_level_of_sensors
      - automation.notify_low_battery

  WiFi:
    entities:
      - sensor.hasikas_iphone_wifi_state
      - sensor.mallikas_iphone_wifi_state
      - sensor.srinikas_iphone_wifi_state
      - sensor.sureshs_iphone_wifi_state

sensor:

  - platform: mqtt
    state_topic: "owntracks/mallika/mallika"
    name: "Mallika's iPhone Battery (OT)"
    unit_of_measurement: "%"
    value_template: "{{ value_json.batt }}"
    
  - platform: mqtt
    state_topic: "owntracks/suresh/suresh"
    name: "Suresh's iPhone Battery (OT)"
    unit_of_measurement: "%"
    value_template: "{{ value_json.batt }}"
  
  - platform: mqtt
    state_topic: "owntracks/srinika/srinika"
    name: "Srinika's iPhone Battery (OT)"
    unit_of_measurement: "%"
    value_template: "{{ value_json.batt }}"
      
  - platform: mqtt
    state_topic: "owntracks/hasika/hasika"
    name: "Hasika's iPhone Battery (OT)"
    unit_of_measurement: "%"
    value_template: "{{ value_json.batt }}"

  - platform: mqtt
    state_topic: "owntracks/mallika/mallika"
    name: "Mallika's iPhone Battery State"
    value_template: >
      {% if value_json.charging == 1 %}
        Charging
      {% else %}
        Not Charging
      {% endif %}

  - platform: mqtt
    state_topic: "owntracks/suresh/suresh"
    name: "Suresh's iPhone Battery State"
    value_template: >
      {% if value_json.charging == 1 %}
        Charging
      {% else %}
        Not Charging
      {% endif %}
  
  - platform: mqtt
    state_topic: "owntracks/srinika/srinika"
    name: "Srinika's iPhone Battery State"
    value_template: >
      {% if value_json.charging == 1 %}
        Charging
      {% else %}
        Not Charging
      {% endif %}

  - platform: mqtt
    state_topic: "owntracks/hasika/hasika"
    name: "Hasika's iPhone Battery State"
    value_template: >
      {% if value_json.charging == 1 %}
        Charging
      {% else %}
        Not Charging
      {% endif %}

  - platform: mqtt
    state_topic: "owntracks/mallika/mallika"
    name: "Mallika's iPhone Wifi State"
    value_template: >
      {% if value_json.wifi == 1 %}
        Connected
      {% else %}
        Not Connected
      {% endif %}

  - platform: mqtt
    state_topic: "owntracks/suresh/suresh"
    name: "Suresh's iPhone Wifi State"
    value_template: >
      {% if value_json.wifi == 1 %}
        Connected
      {% else %}
        Not Connected
      {% endif %}

  - platform: mqtt
    state_topic: "owntracks/srinika/srinika"
    name: "Srinika's iPhone Wifi State"
    value_template: >
      {% if value_json.wifi == 1 %}
        Connected
      {% else %}
        Not Connected
      {% endif %}

  - platform: mqtt
    state_topic: "owntracks/hasika/hasika"
    name: "Hasika's iPhone Wifi State"
    value_template: >
      {% if value_json.wifi == 1 %}
        Connected
      {% else %}
        Not Connected
      {% endif %}

  - platform: template
    sensors:
      suresh_iphone_battery_ot:
        unit_of_measurement: '%'
        entity_id: device_tracker.suresh_suresh
        value_template: >
          {% if states('sensor.sureshs_iphone_battery_ot') != "unknown" %}
            {{ states('sensor.sureshs_iphone_battery_ot')| int }}
          {% else %}
            0
          {% endif %}
        icon_template: >-
          {% if states('sensor.sureshs_iphone_battery_ot') != "unknown" %}
            {% set battery_level = states('sensor.sureshs_iphone_battery_ot')|int (-1)%}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if states.sensor.sureshs_iphone_battery_state.state | lower == "charging" %}
              {% if battery_level == -1 %}
                mdi:battery-unknown
              {% else %}
                {% if battery_round >= 100 %}
                  mdi:battery-charging-100
                {% elif battery_round > 0 %}
                  mdi:battery-charging-{{ battery_round }}
                {% else %}
                  mdi:battery-alert
                {% endif %}
              {% endif %}
            {% else %}
              {% if battery_level == -1 %}
                mdi:battery-unknown
              {% else %}
                {% if battery_round >= 100 %}
                  mdi:battery
                {% elif battery_round > 0 %}
                  mdi:battery-{{ battery_round }}
                {% else %}
                  mdi:battery-alert
                {% endif %}
              {% endif %}            
            {% endif %}
          {% else %}
            mdi:battery-alert
          {% endif %}

  - platform: template
    sensors:
      mallika_iphone_battery_ot:
        unit_of_measurement: '%'
        entity_id: device_tracker.mallika_mallika
        value_template: "{{ states('sensor.mallikas_iphone_battery_ot')|int(-1) }}"
        icon_template: >-
          {% if states('sensor.mallikas_iphone_battery_ot') != "unknown" %}
            {% set battery_level = states('sensor.mallikas_iphone_battery_ot')|int (-1)%}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if states.sensor.mallikas_iphone_battery_state.state | lower == "charging" %}
              {% if battery_level == -1 %}
                mdi:battery-unknown
              {% else %}
                {% if battery_round >= 100 %}
                  mdi:battery-charging-100
                {% elif battery_round > 0 %}
                  mdi:battery-charging-{{ battery_round }}
                {% else %}
                  mdi:battery-alert
                {% endif %}
              {% endif %}
            {% else %}
              {% if battery_level == -1 %}
                mdi:battery-unknown
              {% else %}
                {% if battery_round >= 100 %}
                  mdi:battery
                {% elif battery_round > 0 %}
                  mdi:battery-{{ battery_round }}
                {% else %}
                  mdi:battery-alert
                {% endif %}
              {% endif %}            
            {% endif %}
          {% else %}
            mdi:battery-alert
          {% endif %}
  
  - platform: template
    sensors:
      srinika_iphone_battery_ot:
        unit_of_measurement: '%'
        entity_id: device_tracker.srinika_srinika
        value_template: "{{ states('sensor.srinikas_iphone_battery_ot')|int(-1) }}"
        icon_template: >-
          {% if states('sensor.srinikas_iphone_battery_ot') != "unknown" %}
            {% set battery_level = states('sensor.srinikas_iphone_battery_ot')|int (-1)%}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if states.sensor.srinikas_iphone_battery_state.state | lower == "charging" %}
              {% if battery_level == -1 %}
                mdi:battery-unknown
              {% else %}
                {% if battery_round >= 100 %}
                  mdi:battery-charging-100
                {% elif battery_round > 0 %}
                  mdi:battery-charging-{{ battery_round }}
                {% else %}
                  mdi:battery-alert
                {% endif %}
              {% endif %}
            {% else %}
              {% if battery_level == -1 %}
                mdi:battery-unknown
              {% else %}
                {% if battery_round >= 100 %}
                  mdi:battery
                {% elif battery_round > 0 %}
                  mdi:battery-{{ battery_round }}
                {% else %}
                  mdi:battery-alert
                {% endif %}
              {% endif %}            
            {% endif %}
          {% else %}
            mdi:battery-alert
          {% endif %}
  
  - platform: template
    sensors:
      hasika_iphone_battery_ot:
        unit_of_measurement: '%'
        entity_id: device_tracker.hasika_hasika
        value_template: "{{ states('sensor.hasikas_iphone_battery_ot')|int(-1) }}"
        icon_template: >-
          {% if states('sensor.hasikas_iphone_battery_ot') != "unknown" %}
            {% set battery_level = states('sensor.hasikas_iphone_battery_ot')|int (-1)%}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if states.sensor.hasikas_iphone_battery_state.state | lower == "charging" %}
              {% if battery_level == -1 %}
                mdi:battery-unknown
              {% else %}
                {% if battery_round >= 100 %}
                  mdi:battery-charging-100
                {% elif battery_round > 0 %}
                  mdi:battery-charging-{{ battery_round }}
                {% else %}
                  mdi:battery-alert
                {% endif %}
              {% endif %}
            {% else %}
              {% if battery_level == -1 %}
                mdi:battery-unknown
              {% else %}
                {% if battery_round >= 100 %}
                  mdi:battery
                {% elif battery_round > 0 %}
                  mdi:battery-{{ battery_round }}
                {% else %}
                  mdi:battery-alert
                {% endif %}
              {% endif %}            
            {% endif %}
          {% else %}
            mdi:battery-alert
          {% endif %}

automation:

###############################################################################
# Automation: Notify of iPhone Low Battery
###############################################################################
  - alias: Notify Low battery
    initial_state: true
    trigger:
      platform: numeric_state
      entity_id:
      - device_tracker.suresh_suresh
      - device_tracker.mallika_mallika
      - device_tracker.srinika_srinika
      - device_tracker.hasika_hasika
      value_template: '{{ state.attributes.battery }}'
      below: 25
    action:
      - service: script.notify_me
        data_template:
          value1: "{{ trigger.to_state.attributes.friendly_name }}'s phone battery is less than: {{ trigger.to_state.attributes.battery }}%."
          value2: ""
      - service: script.voice_notify
        data_template:
          value1: "{{ trigger.to_state.attributes.friendly_name }}'s phone battery is less than: {{ trigger.to_state.attributes.battery }}%."
      # - service: mqtt.publish
        # data_template:
          # topic: /dump/numeric_state
          # retain: false
          # payload: >-
            # {% macro dumpState(type, stateObj) %}
              # type ~ ".state: " {{ stateObj.state }}{{- "\n" -}}
              # type ~ ".entity_id: " {{ stateObj.entity_id }}{{- "\n" -}}
              # type ~ ".domain: " {{ stateObj.domain }}{{- "\n" -}}
              # type ~ ".object_id: " {{ stateObj.object_id }}{{- "\n" -}}
              # type ~ ".name: " {{ stateObj.name }}{{- "\n" -}}
              # type ~ ".state.last_updated: "{{ stateObj.state.last_updated }}{{- "\n" -}}
              # type ~ ".state.last_changed: " {{ stateObj.state.last_changed }}{{- "\n" -}}
              # type ~ ".state.attributes: "{{- "\n" -}}
              # {%- for attrib in stateObj.attributes | sort() %}
                # {%- if attrib is defined %} 
                  # {{attrib}}: {{ item.attributes[attrib] }}{{- "\n" -}}
                # {%- endif %}
              # {% endfor %}
            # {% endmacro %}
            # trigger.platform: {{ trigger.platform }}{{- "\n" -}}
            # trigger.entity_id: {{ trigger.entity_id }}{{- "\n" -}}
            # trigger.below: {{trigger.below }}{{- "\n" -}}
            # trigger.above: {{ trigger.above }}{{- "\n" -}}
            # trigger.from_state Attributes: {{ dumpState("trigger.from_state.state", trigger.from_state) }} {{- "\n" -}}
            # trigger.to_state Attributes: {{ dumpState("trigger.to_state.state", trigger.to_state) }}

# ###############################################################################
# # Automation: Notify of Sensor's Low Battery
# ###############################################################################
  - alias: Alert Low Battery Level of Sensors
    initial_state: true
    trigger:
      platform: numeric_state
      entity_id:
      - sensor.upstairs_multisensor_battery
      - sensor.downstairs_multisensor_battery
      - sensor.single_car_garage_door_sensor_battery
      - sensor.two_car_garage_door_sensor_battery
      - sensor.frontroom_multisensor_battery
      below: 10
    condition:
      - condition: template
        value_template: >-
          {%- if states.sensor.upstairs_multisensor_battery -%}
            true
          {%- else -%}
            true
          {%- endif -%}
      - condition: template
        value_template: >-
          {%- if states.sensor.downstairs_multisensor_battery -%}
            true
          {%- else -%}
            true
          {%- endif -%}
      - condition: template
        value_template: >-
          {%- if states.sensor.single_car_garage_door_sensor_battery -%}
            true
          {%- else -%}
            true
          {%- endif -%}
      - condition: template
        value_template: >-
          {%- if states.sensor.two_car_garage_door_sensor_battery -%}
            true
          {%- else -%}
            true
          {%- endif -%}
      - condition: template
        value_template: >-
          {%- if states.sensor.frontroom_multisensor_battery -%}
            true
          {%- else -%}
            true
          {%- endif -%}
      - condition: template
        value_template: "{{ trigger.to_state.state != 'unknown' and trigger.from_state.state != 'unknown'}}"
      - condition: template
        value_template: "{{ trigger.to_state.state > 0 and trigger.to_state.state < 10 }}"
    action:
      - service: script.notify_me
        data_template:
          value1: "Attention! {{ trigger.to_state.attributes.friendly_name }} level is: {{ trigger.to_state.state }}%."
          value2: ""
      - service: script.voice_notify
        data_template:
          value1: "Attention! {{ trigger.to_state.attributes.friendly_name }} level is: {{ trigger.to_state.state }}%."
          
  - alias: Check Wi-Fi Status of iPhones At Home
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - device_tracker.mallika_mallika
          - device_tracker.suresh_suresh
          - device_tracker.srinika_srinika
          - device_tracker.hasika_hasika
        from: 'not_home'
        to: 'home'
        for: '00:05:00'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: sensor.hasikas_iphone_wifi_state
          state: 'Not Connected'
        - condition: state
          entity_id: sensor.mallikas_iphone_wifi_state
          state: 'Not Connected'
        - condition: state
          entity_id: sensor.srinikas_iphone_wifi_state
          state: 'Not Connected'
        - condition: state
          entity_id: sensor.sureshs_iphone_wifi_state
          state: 'Not Connected'
    action:
      - service: script.notify_me
        data_template:
          value1: >
            {% set member = trigger.entity_id.split('.')[1].split('_')[0] %}
            {% if member == "sureshs" %}
              Suresh's iPhone is not connected to Wi-Fi at home!
            {% elif member == "mallikas" %}
              Mllika's iPhone is not connected to Wi-Fi at home!
            {% elif member == "srinikas" %}
              Srinika's iPhone is not connected to Wi-Fi at home!
            {% elif member == "hasikas" %}
              Hasika's iPhone is not connected to Wi-Fi at home!
            {% endif %}
          value2: ""
      - service: script.voice_notify
        data_template:
          value1: >
            {% set member = trigger.entity_id.split('.')[1].split('_')[0] %}
            {% if member == "sureshs" %}
              Suresh's iPhone is not connected to Wi-Fi at home!
            {% elif member == "mallikas" %}
              Mllika's iPhone is not connected to Wi-Fi at home!
            {% elif member == "srinikas" %}
              Srinika's iPhone is not connected to Wi-Fi at home!
            {% elif member == "hasikas" %}
              Hasika's iPhone is not connected to Wi-Fi at home!
            {% endif %}
