homeassistant:
  customize:
    # Garage Door Tilt Sensors
    zwave.ecolink_garage_door_tilt_sensor_4:
      hidden: false
      friendly_name: 2-Car Garage Door Sensor

    zwave.ecolink_garage_door_tilt_sensor_5:
      hidden: false
      friendly_name: 1-Car Garage Door Sensor

    sensor.mqtt_single_car_garage_status:
      friendly_name: 1 Car Garage State in MQTT
      hidden: false

    sensor.mqtt_double_car_garage_status:
      friendly_name: 2 Car Garage State in MQTT
      hidden: false

# Single Car Garage Door Sensor
    # sensor.ecolink_garage_door_tilt_sensor_sourcenodeid_5_2:
      # hidden: true
    # sensor.ecolink_garage_door_tilt_sensor_power_management_5_11:
      # hidden: true
    # sensor.ecolink_garage_door_tilt_sensor_burglar_5_10:
       # hidden: true
    # sensor.ecolink_garage_door_tilt_sensor_alarm_type_5_0:
      # hidden: true
    # sensor.ecolink_garage_door_tilt_sensor_alarm_level_5_1:
      # hidden: true
    # sensor.ecolink_garage_door_tilt_sensor_access_control_5_9:
      # hidden: true
    binary_sensor.ecolink_garage_door_tilt_sensor_sensor_2:
      hidden: true
      device_class: opening
      friendly_name: Single Car Garage Door
    sensor.single_car_garage_door_sensor_status:
      hidden: false
      friendly_name: Single Car Garage Door
      device_class: opening

# Double Car Garage Door Sensor
    # sensor.ecolink_garage_door_tilt_sensor_access_control_4_9:
      # hidden: true
    # sensor.ecolink_garage_door_tilt_sensor_burglar_4_10:
      # hidden: true
    # sensor.ecolink_garage_door_tilt_sensor_power_management_4_11:
      # hidden: true
    # sensor.ecolink_garage_door_tilt_sensor_sourcenodeid_4_2:
      # hidden: true
    # sensor.ecolink_garage_door_tilt_sensor_alarm_level_4_1:
      # hidden: true
    # sensor.ecolink_garage_door_tilt_sensor_alarm_type_4_0:
      # hidden: true
    binary_sensor.ecolink_garage_door_tilt_sensor_sensor:
      hidden: true
      device_class: opening
      friendly_name: Double Car Garage Door
    sensor.two_car_garage_door_sensor_status:
      hidden: false
      friendly_name: Double Car Garage Door
      device_class: opening

switch:
  - platform: tplink
    host: !secret tplink_garage
    name: Garage Lights

  - platform: mqtt
    name: "Single Car Garage"
    state_topic: "/home/1cargarage/onoff"
    command_topic: "/home/1cargarage/onoff"
    payload_on: "ON"
    payload_off: "OFF"

  - platform: mqtt
    name: "Double Car Garage"
    state_topic: "/home/2cargarage/onoff"
    command_topic: "/home/2cargarage/onoff"
    payload_on: "ON"
    payload_off: "OFF"

group:
  Garage:
    entities:
      - switch.garage_lights
      - switch.single_car_garage
      - switch.double_car_garage
      - sensor.single_car_garage_door_sensor_status
      - sensor.two_car_garage_door_sensor_status
      - input_boolean.working_in_garage
      - automation.notify_garage_door_status
      - sensor.mqtt_single_car_garage_status
      - sensor.mqtt_double_car_garage_status

sensor:

  - platform: mqtt
    state_topic: "/home/1cargarage/onoff"
    name: "MQTT Single Car Garage Status"
    value_template: "{{ value }}"

  - platform: mqtt
    state_topic: "/home/2cargarage/onoff"
    name: "MQTT Double Car Garage Status"
    value_template: "{{ value }}"

  - platform: template
    sensors:
      single_car_garage_door_sensor_battery:
        value_template: "{{ (states.zwave.ecolink_garage_door_tilt_sensor_2.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Single Car Garage Door Sensor Battery
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.single_car_garage_door_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: template
    sensors:
      two_car_garage_door_sensor_battery:
        value_template: "{{ (states.zwave.ecolink_garage_door_tilt_sensor.attributes|default).battery_level|default|int('unknown') }}"
        friendly_name: Double Car Garage Door Sensor Battery
        unit_of_measurement: "%"
        icon_template: >-
          {% set battery_level = states('sensor.two_car_garage_door_sensor_battery')|int('unknown') %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% set battery_round = (battery_level|int / 10)|int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: template
    sensors:
      single_car_garage_door_sensor_status:
        friendly_name: Single Car Garage Door Sensor Status
        value_template: >-
          {% if states.binary_sensor.ecolink_garage_door_tilt_sensor_sensor_2.state == 'on' %}
            Open
          {% elif states.binary_sensor.ecolink_garage_door_tilt_sensor_sensor_2.state == 'off' %}
            Closed
          {% else %}
            Unknown
          {% endif %}
        icon_template: >-
          {% set door_status = states.binary_sensor.ecolink_garage_door_tilt_sensor_sensor_2.state |d('unknown') %}
          {% if door_status == 'unknown' %}
            mdi:alert-circle
          {% else %}
            {% if door_status == 'on' %}
              mdi:garage-open
            {% else %}
              mdi:garage
            {% endif %}
          {% endif %}
  
  - platform: template
    sensors:
      two_car_garage_door_sensor_status:
        value_template: >-
          {% if states.binary_sensor.ecolink_garage_door_tilt_sensor_sensor.state == 'on' %}
            Open
          {% elif states.binary_sensor.ecolink_garage_door_tilt_sensor_sensor.state == 'off' %}
            Closed
          {% else %}
            Unknown
          {% endif %}
        friendly_name: Double Car Garage Door Sensor Status
        icon_template: >-
          {% set door_status = states.binary_sensor.ecolink_garage_door_tilt_sensor_sensor.state |d('unknown') %}
          {% if door_status == 'unknown' %}
            mdi:alert-circle
          {% else %}
            {% if door_status == 'on' %}
              mdi:garage-open
            {% else %}
              mdi:garage
            {% endif %}
          {% endif %}

automation:

################################################################################
# Notifies when either of the garage door is opened or closed
# When the garage is opened, it sends an actionable ios notification with an 
# option to close the garage door. This iso actionable notification only occurs 
# when garage door is open and not when it is closed.
###############################################################################
  - alias: Notify Garage Door Status
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: 
      - binary_sensor.ecolink_garage_door_tilt_sensor_sensor
      - binary_sensor.ecolink_garage_door_tilt_sensor_sensor_2
    condition:
      - condition: template
        value_template: "{% if trigger.from_state %} True {% else %} False {% endif %}"
    action:
      - service: script.notify_me
        data_template:
          value1: >
              {% if trigger.to_state.state | lower == "on" %}
                  {{ trigger.to_state.attributes.friendly_name }} is now OPENED!
              {% elif trigger.to_state.state | lower == "off" %}
                  {{ trigger.to_state.attributes.friendly_name }} is now CLOSED!
              {% endif %}
          value2: ""
      - service_template: >
          {% if trigger.to_state.state | lower == "on" %}
            switch.turn_on
          {% else %}
            switch.turn_off
          {% endif%}
        data:
          entity_id: switch.garage_lights
      - service: mqtt.publish
        data_template:
          topic: >
            {% if trigger.entity_id == "binary_sensor.ecolink_garage_door_tilt_sensor_sensor" %}
              /home/1cargarage/onoff
            {% else %}
              /home/2cargarage/onoff
            {% endif %}
          payload: 'OFF'
      - service: script.voice_notify
        data_template:
          value1: >
            {% if trigger.to_state.state | lower == "on" %}
              Attention! Your {{ trigger.to_state.attributes.friendly_name }} is now OPENED!
            {% elif trigger.to_state.state | lower == "off" %}
              Your {{ trigger.to_state.attributes.friendly_name }} is now CLOSED!
            {% endif %}
      - condition: and
        conditions:
          - condition: template
            value_template: >
              {% if trigger.to_state.state | lower == "on" %}
                true
              {% else %}
                false
              {% endif %}
      - service: notify.ios_suresh
        data_template:
          title: >
            {{ trigger.to_state.attributes.friendly_name }}
          message: >
            Attention: Your {{ trigger.to_state.attributes.friendly_name }} is now OPENED!
          data:
            push:
              badge: 0
              category: >
                {% if trigger.entity_id == "binary_sensor.ecolink_garage_door_tilt_sensor_sensor_2" %}
                  1CAR_GARAGE
                {% else %}
                 2CAR_GARAGE
                {% endif%}

################################################################################
#  iOS Actionable Notification for Single Car Garage Door
################################################################################
  - alias: Close Single Car Garage Door
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: 1CAR_GARAGE_CLOSE
    action:
      - service: notify.ios_suresh
        data:
          message: "Closing Single Car Garage Door.."
      - service: switch.turn_off
        entity_id: switch.single_car_garage

################################################################################
#  iOS Actionable Notification for Double Car Garage Door
################################################################################
  - alias: Close Double Car Garage Door
    initial_state: true
    hide_entity: true
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: 2CAR_GARAGE_CLOSE
    action:
      - service: notify.ios_suresh
        data:
          message: "Closing Double Car Garage Door.."
      - service: switch.turn_off
        entity_id: switch.double_car_garage
