###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   04/15/2017
#   @package        :   Lights
#   @description    :   Lights, Lights, Lights! All the Lights are here!
###############################################################################
homeassistant:
  customize:
  
    group.lights:
      order: 8
    group.light_automations:
      order: 9

    switch.wemofrontporchlightswitch:
      friendly_name: Front Porch Lights
      icon: mdi:lightbulb
    switch.wemoswitch1:
      friendly_name: Front Room Light
      icon: mdi:lamp
    switch.wemobackyardlightswitch:
      friendly_name: Backyard Lights
      icon: mdi:lightbulb

    light.dinette:
      friendly_name: Kitchen Light
    light.hue_color_lamp_1:
      friendly_name: Family Room Light 1
    light.hue_color_lamp_2:
      friendly_name: Family Room Light 2
    light.hue_color_lamp_3:
      friendly_name: Family Room Light 3
      
    input_boolean.short_flash:
      friendly_name: Short Flash
      icon: mdi:flash
    input_boolean.long_flash:
      friendly_name: Long Flash
      icon: mdi:flash      
    input_boolean.animate_downstairs_lights:
      friendly_name: Animate Family Room Lights    
      icon: mdi:flash-outline
    input_boolean.animate_upstairs_lights:
      friendly_name: Animate Master Bedroom Lights
      icon: mdi:flash-outline
      
    script.start_colorloop:
      friendly_name: Start Colorloop
      icon: mdi:palette
    script.stop_colorloop:
      friendly_name: Stop Colorloop
      icon: mdi:palette
    script.lifx_breathe:
      friendly_name: Lifx Breath
      icon: mdi:lightbulb      

group:
  Lights:
    entities:
      - light.dinette
      - switch.kids_bedroom
      - switch.guest_bedroom_1
      - switch.guest_bedroom_2
      - light.hue_color_lamp_1
      - light.hue_color_lamp_2
      - light.hue_color_lamp_3
      - light.family_room
      - light.master_bedroom_1
      - light.master_bedroom_2
      - light.master_bedroom
      - switch.wemofrontporchlightswitch
      - switch.wemobackyardlightswitch
      - switch.wemoswitch1
      - switch.garage_lights

  Light Automations:
    control: hidden
    entities:
      - automation.animate_master_bedroom_lights
      - input_boolean.animate_kitchen_lights
      - input_boolean.animate_downstairs_lights
      - input_boolean.animate_upstairs_lights
      - input_boolean.short_flash
      - input_boolean.long_flash

light:
  - platform: lifx
    broadcast: !secret lifx_broadcast_ip
  - platform: hue
    host: !secret philips_hue_ipaddress

switch:
  - platform: tplink
    host: !secret tplink_kids_bedroom
    name: Kids Bedroom
  - platform: tplink
    host: !secret tplink_guest_bedroom_1
    name: Guest Bedroom 1
  - platform: tplink
    host: !secret tplink_guest_bedroom_2
    name: Guest Bedroom 2

wemo:
  static:
    - !secret wemo_switch_1
    - !secret wemo_switch_2
    - !secret wemo_switch_3

input_boolean:
  animate_upstairs_lights:
    name: Animate Master Bedroom Lights
    initial: off
  animate_downstairs_lights:
    name: Animate Family Room Lights
    initial: off
  animate_kitchen_lights:
    name: Animate Kitchen Lights
    initial: off
  long_flash:
    name: Long Flash Lights
    initial: off
  short_flash:
    name: Long Flash Lights
    initial: off

script:
  start_colorloop:
    sequence:
      - service: light.lifx_effect_colorloop
        data:
          entity_id: light.dinette
          brightness: 255
          period: 2
          spread: 360
          change: 35

  stop_colorloop:
    sequence:
      - service: light.lifx_effect_stop
        data:
          entity_id: light.dinette

  lifx_breathe:
    sequence:
      - service: light.lifx_effect_pulse
        data:
          mode: breathe
          entity_id: light.dinette
          color_name: red
          cycles: 3
          power_on: true

automation:
  - alias: Animate Master Bedroom Lights
    initial_state: true
    hide_entity: True
    trigger:
      platform: time
      seconds: '/5'
    condition:
      - condition: state
        entity_id: input_boolean.animate_upstairs_lights
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: group.master_bedroom_lights
          transition: 5
          brightness: 255
          color_temp: 366
        data_template:
          rgb_color: ['{{ "{0:d}".format(range(0, 255)|random) }}' , '{{ "{0:d}".format(range(0, 255)|random) }}', '{{ "{0:d}".format(range(0, 255)|random) }}']
  
  - alias: Restore Masterbedroom Lights
    initial_state: true
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_boolean.animate_upstairs_lights
      to: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: group.master_bedroom_lights
          transition: 5
          rgb_color: [224,175,102]
          brightness: 10
          color_temp: 366
  
  - alias: Animate Familyroom Lights
    initial_state: true
    hide_entity: true
    trigger:
      platform: time
      seconds: '/5'
    condition:
      - condition: state
        entity_id: input_boolean.animate_downstairs_lights
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: group.family_room_lights
          transition: 5
          brightness: 255
          color_temp: 366
        data_template:
          rgb_color: ['{{ "{0:d}".format(range(0, 255)|random) }}' , '{{ "{0:d}".format(range(0, 255)|random) }}', '{{ "{0:d}".format(range(0, 255)|random) }}']
          
  - alias: Restore Familyroom Lights
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: input_boolean.animate_downstairs_lights
      to: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: group.family_room_lights
          transition: 5
          rgb_color: [255, 251, 245]
          brightness: 255
          color_temp: 162
        
  - alias: Animate Kitchen Lights ON
    initial_state: true
    hide_entity: true
    trigger:
      - platform: time
        seconds: '/3'
    condition:
      - condition: state
        entity_id: input_boolean.animate_kitchen_lights
        state: 'on'
    action:
      - service: light.turn_on
        entity_id: light.dinette
        data_template:
          rgb_color: ['{{ (range(0, 255)|random) }}', '{{ (range(0, 255)|random) }}', '{{ (range(0, 255)|random) }}']
          brightness: 255
          transition: '{{ (range(1, 2)|random) }}'
  
  - alias: Animate Kitchen Lights OFF
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.animate_kitchen_lights
        to: 'off'
    action:
      - service: light.turn_on
        entity_id: light.dinette
        data:
          rgb_color: [255, 255, 255]
          brightness: 255
          color_temp: 155
  
  - alias: Long Flash all lights
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.long_flash
        to: 'on'
        from: 'off'
    action:
      - service: light.turn_on
        entity_id:
          - group.all_lights
        data:
          flash: long
      - service: input_boolean.turn_off
        entity_id: input_boolean.long_flash
  
  - alias: Short Flash all_lights
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.short_flash
        to: 'on'
        from: 'off'
    action:
      - service: light.turn_on
        entity_id:
          - group.all_lights
        data:
          flash: short
      - service: input_boolean.turn_off
        entity_id: input_boolean.short_flash

  # - alias: Random Light Effects
    # initial_state: true
    # trigger:
      # - platform: time
        # minutes: '00'
        # seconds: '/15'
    # action:
      # - service: script.turn_on
        # data_template:
          # entity_id: >-
            # {{ [ 'script.start_colorloop',
                 # 'script.stop_colorloop',
                 # 'script.lifx_breathe' ] |random 
            # }}

  # - alias: Test Kitchen Light
    # trigger:
      # platform: state
      # entity_id: light.dinette
    # action:
      # - service: logbook.log
        # data_template:
          # name: "Dump of {{ trigger.platform }}"
          # message: >-
            # {%- macro dumpState(statePrefix, stateObj) -%}
              # {{statePrefix ~ ": "}} {{- stateObj.state }}{{- "\n" -}}
              # {{statePrefix ~ ".entity_id: "}} {{- stateObj.entity_id }}{{- "\n" -}}
              # {{statePrefix ~ ".domain: "}} {{- stateObj.domain }}{{- "\n" -}}
              # {{statePrefix ~ ".object_id: "}} {{- stateObj.object_id }}{{- "\n" -}}
              # {{statePrefix ~ ".name: "}} {{- stateObj.name }}{{- "\n" -}}
              # {{statePrefix ~ ".last_updated: "}} {{- stateObj.last_updated }}{{- "\n" -}}
              # {{statePrefix ~ ".last_changed: "}} {{- stateObj.last_changed }}{{- "\n" -}}
              # {%- for attrib in stateObj.attributes | sort() %}
                # {%- if attrib is defined -%} 
                # {{- statePrefix ~ ".attributes." ~ attrib ~ ": " -}} {{- stateObj.attributes[attrib] -}}
                # {{- "\n" -}}
                # {%- endif -%}
              # {%- endfor -%}
            # {%- endmacro -%}
            
            # {% set p = trigger.platform %}
            # {{"trigger.platform: "}} {{ p }}{{- "\n" -}}
            
            # {%- if p == "mqtt" -%}
            # {{"trigger.topic: "}} {{ trigger.topic }}{{- "\n" -}}
            # {{"trigger.payload: "}} {{ trigger.payload }}{{- "\n" -}}
            # {{"trigger.payload_json: "}} {{ trigger.payload_json }}{{- "\n" -}}
            # {{"trigger.qos: "}} {{ trigger.qos }}{{- "\n" -}}
            # {%- endif -%}
            
            # {%- if p == "event" or p == "sun" or p == "zone" -%}
            # {{"trigger.event: "}} {{ trigger.event }}{{- "\n" -}}
            # {%- endif -%}
            
            # {%- if p == "numeric_state" -%}
            # {{"trigger.above: "}} {{ trigger.above }}{{- "\n" -}}
            # {{"trigger.below: "}} {{trigger.below }}{{- "\n" -}}
            # {%- endif -%}
            
            # {%- if p == "state" -%}
            # {{"trigger.for: "}} {{ trigger.for }}{{- "\n" -}}
            # {%- endif -%}
            
            # {%- if p == "time" -%}
            # {{"trigger.now: "}} {{ trigger.now }}{{- "\n" -}}
            # {%- endif -%}
            
            # {%- if p == "zone" -%}
            # {{"trigger.zone: "}} {{ trigger.zone }}{{- "\n" -}}
            # {%- endif -%}
            
            # {%- if p == "state" or p == "numeric_state" or p == "template" or p == "zone" -%}
            # {{"trigger.entity_id: "}} {{ trigger.entity_id }}{{- "\n" -}}{{- "\n" -}}
            # {{"trigger.from_state: "}} {{- "\n" -}}
            # -------------------{{- "\n" -}}
            # {{ dumpState("trigger.from_state", trigger.from_state) }} {{- "\n" -}}
            # trigger.to_state:{{- "\n" -}}
            # -----------------{{- "\n" -}}
            # {{ dumpState("trigger.to_state", trigger.to_state) }}            
            # {%- endif -%}
