###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   07/16/2017
#   @package        :   QNAP
#   @description    :   QNAP NAS Package
###############################################################################
homeassistant:
  customize:
    sensor.kalavalanas_cpu_usage:
      friendly_name: CPU Usage
    sensor.kalavalanas_memory_usage:
      friendly_name: Memory Usage
    sensor.kalavalanas_network_up_eth0:
      friendly_name: Network Speed
    sensor.kalavalanas_network_up_eth1:
      friendly_name: Network Speed
    sensor.kalavalanas_status:
      friendly_name: NAS Status
    sensor.kalavalanas_volume_used_datavol1:
      friendly_name: Percent Disk Used
    sensor.kalavalanas_system_temp:
      friendly_name: System Temperature
    sensor.kalavalanas_cpu_temp:
      friendly_name: CPU Temperature
    sensor.kalavalanas_drive_smart_status:
      friendly_name: Drive Smart Status
    sensor.kalavalanas_drive_temp:
      friendly_name: Drive Temperature

    sensor.kalavalanas_smart_status_drive_01:
      friendly_name: Drive 1 Status
    sensor.kalavalanas_smart_status_drive_02:
      friendly_name: Drive 2 Status
    sensor.kalavalanas_smart_status_drive_03:
      friendly_name: Drive 3 Status
    sensor.kalavalanas_smart_status_drive_04:
      friendly_name: Drive 4 Status
    
    sensor.kalavalanas_temperature_drive_01:
      friendly_name: Drive 1 Temperature
    sensor.kalavalanas_temperature_drive_02:
      friendly_name: Drive 2 Temperature
    sensor.kalavalanas_temperature_drive_03:
      friendly_name: Drive 3 Temperature
    sensor.kalavalanas_temperature_drive_04:
      friendly_name: Drive 4 Temperature

group:
  QNAP Drive 1:
    entities:
      - sensor.kalavalanas_smart_status_drive_01
      - sensor.kalavalanas_temperature_drive_01

  QNAP Drive 2:
    entities:
      - sensor.kalavalanas_smart_status_drive_02
      - sensor.kalavalanas_temperature_drive_02

  QNAP Drive 3:
    entities:
      - sensor.kalavalanas_smart_status_drive_03
      - sensor.kalavalanas_temperature_drive_03

  QNAP Drive 4:
    entities:
      - sensor.kalavalanas_smart_status_drive_04
      - sensor.kalavalanas_temperature_drive_04

  QNAP Server:
    entities:
      - sensor.kalavalanas_status
      - sensor.kalavalanas_cpu_usage
      - sensor.kalavalanas_memory_usage
      - sensor.kalavalanas_network_up_eth0
      - sensor.kalavalanas_network_up_eth1
      - sensor.kalavalanas_volume_used_datavol1
      - sensor.kalavalanas_drive_smart_status
      - sensor.kalavalanas_drive_temp
      - sensor.kalavalanas_system_temperature
      - sensor.kalavalanas_cpu_temperature

  QNAP Automations:
    entities:
      - automaton.notify_nas_drive_status_change
      - automaton.notify_nas_status_change

  NAS:
    view: yes
    name: NAS
    icon: mdi:harddisk
    entities:
      - group.qnap_server
      - group.qnap_drive_1
      - group.qnap_drive_2
      - group.qnap_drive_3
      - group.qnap_drive_4
      - group.qnap_automations
      
sensor:
  - platform: qnap
    host: 192.168.1.164
    username: !secret qnap_username
    password: !secret qnap_password
    monitored_conditions:
      - status
      - cpu_usage
      - memory_percent_used
      - network_tx
      - volume_percentage_used
      - system_temp
      - cpu_temp
      - drive_smart_status
      - drive_temp

automation:
  - alias: Notify NAS Status Change
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: 
       - sensor.kalavalanas_status
    condition:
      - condition: template
        value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
    action:
      - service: script.notify_me
        data_template:
          value1: "NAS Status changed to: {{ trigger.to_state.state| upper }}"
          value2: ""

  - alias: Notify NAS Drive Status Change
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: 
       - sensor.kalavalanas_smart_status_drive_01
       - sensor.kalavalanas_smart_status_drive_02
       - sensor.kalavalanas_smart_status_drive_03
       - sensor.kalavalanas_smart_status_drive_04
    condition:
      - condition: template
        value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"       
    action:
      - service: script.notify_me
        data_template:
          value1: "NAS Drive state changed to: {{ trigger.to_state.state| upper }} from '{{ trigger.from_state.state| upper }}'"
          value2: ""
